import Foundation

/// Weld vertices — by distance threshold, or all selected onto an explicit
/// target vertex. Faces that collapse below 3 distinct vertices are removed.
public enum MergeVertices: MeshOp {
    public static let name = "Merge"

    public enum Params: Sendable {
        case byDistance(Double)
        /// Merge every selected vertex onto `target` (target keeps its position).
        case toVertex(VertexID)
    }

    public static func apply(_ mesh: HalfEdgeMesh, selection: ComponentSelection,
                             params: Params) throws -> MeshOpResult {
        guard case .vertices(let selected) = selection, !selected.isEmpty else {
            throw MeshOpError.emptySelection
        }
        for v in selected where mesh.positions[v] == nil {
            throw MeshOpError.unknownComponent("vertex \(v.rawValue)")
        }

        // vertex → representative it merges into
        var remap: [VertexID: VertexID] = [:]

        switch params {
        case .toVertex(let target):
            guard mesh.positions[target] != nil else {
                throw MeshOpError.unknownComponent("target vertex \(target.rawValue)")
            }
            for v in selected where v != target { remap[v] = target }

        case .byDistance(let threshold):
            guard threshold > 0 else {
                throw MeshOpError.preconditionFailed("merge distance must be > 0")
            }
            // Union-find over selected vertices within threshold (v1: O(n²),
            // fine at repair-selection scale).
            let verts = selected.sorted()
            var parent: [VertexID: VertexID] = [:]
            func find(_ v: VertexID) -> VertexID {
                var r = v
                while let p = parent[r], p != r { r = p }
                return r
            }
            for v in verts { parent[v] = v }
            for i in verts.indices {
                for j in (i + 1)..<verts.count {
                    let a = verts[i], b = verts[j]
                    if simd_length(mesh.positions[a]! - mesh.positions[b]!) <= threshold {
                        parent[find(b)] = find(a)
                    }
                }
            }
            var clusters: [VertexID: [VertexID]] = [:]
            for v in verts { clusters[find(v), default: []].append(v) }
            for (rep, members) in clusters where members.count > 1 {
                for m in members where m != rep { remap[m] = rep }
            }
        }

        guard !remap.isEmpty else {
            throw MeshOpError.preconditionFailed("no vertices within merge range")
        }

        var out = mesh
        // Cluster centroid for byDistance; toVertex keeps target position.
        if case .byDistance = params {
            var clusterMembers: [VertexID: [VertexID]] = [:]
            for (m, rep) in remap { clusterMembers[rep, default: [rep]].append(m) }
            for (rep, members) in clusterMembers {
                var c = SIMD3<Double>()
                for m in members { c += mesh.positions[m]! }
                out.setPosition(c / Double(members.count), for: rep)
            }
        }

        var degenerate = Set<FaceID>()
        for f in mesh.faceOrder {
            let loop = mesh.faceLoops[f]!
            var newLoop = loop.map { remap[$0] ?? $0 }
            // Collapse consecutive duplicates (including around the wrap).
            var compact: [VertexID] = []
            for v in newLoop where compact.last != v { compact.append(v) }
            while compact.count > 1, compact.first == compact.last { compact.removeLast() }
            newLoop = compact
            if newLoop.count < 3 || Set(newLoop).count != newLoop.count {
                degenerate.insert(f) // face degenerated by the weld
            } else if newLoop != loop {
                out.replaceLoop(newLoop, for: f)
            }
        }
        out.removeFaces(degenerate)
        out.removeVertices(Set(remap.keys))
        out.pruneIsolatedVertices()

        let delta = TopologyDelta(vertices: out.vertexCount - mesh.vertexCount,
                                  edges: out.edgeCount - mesh.edgeCount,
                                  faces: out.faceCount - mesh.faceCount)
        try OpSupport.verify(before: mesh, after: out, predicted: delta)
        let survivors = Set(remap.values).filter { out.positions[$0] != nil }
        return MeshOpResult(mesh: out, resultSelection: .vertices(survivors), delta: delta)
    }
}
